// Generated by CoffeeScript 1.7.1
require.config({
  paths: {
    'jquery': 'lib/jquery'
  },
  shim: {
    'lib/underscore': {
      exports: '_'
    },
    'lib/backbone': {
      deps: ['lib/underscore', 'jquery'],
      exports: 'Backbone'
    }
  }
});

require(['jquery', 'lib/underscore', 'vcs/gallery'], function($, _, Gallery) {
  return $(function() {
    console.log('Pravo!');
    return new Gallery({
      root: 'gallery',
      template: 'gallery'
    });
  });
});
