// Generated by CoffeeScript 1.9.3
require.config({
  paths: {
    'jquery': 'lib/jquery'
  },
  shim: {
    'lib/underscore': {
      exports: '_'
    },
    'lib/backbone': {
      deps: ['lib/underscore', 'jquery'],
      exports: 'Backbone'
    }
  }
});

require(['jquery', 'lib/underscore', 'vcs/pravo'], function($, _, Pravo) {
  return $(function() {
    return new Pravo;
  });
});
