// Generated by CoffeeScript 1.9.3
require.config({
  paths: {
    'jquery': 'lib/jquery'
  },
  shim: {
    'lib/underscore': {
      exports: '_'
    },
    'lib/backbone': {
      deps: ['lib/underscore', 'jquery'],
      exports: 'Backbone'
    }
  }
});

require(['jquery', 'lib/underscore', 'vcs/dashboard'], function($, _, Dashboard) {
  return $(function() {
    var dashboard;
    dashboard = new Dashboard({
      root: 'dashboard',
      template: 'dashboard'
    });
    window.Pravo = {};
    return Pravo.cleanLocalArtworks = function() {
      return dashboard.gallery.artworks.cleanLocal();
    };
  });
});
