// Generated by CoffeeScript 1.9.3
require.config({
  paths: {
    'jquery': 'lib/jquery'
  },
  shim: {
    'lib/underscore': {
      exports: '_'
    },
    'lib/backbone': {
      deps: ['lib/underscore', 'jquery'],
      exports: 'Backbone'
    }
  }
});

require(['jquery', 'lib/underscore', 'vc/dashboard'], function($, _, DashboardVC) {
  return $(function() {
    var dashboard;
    console.debug('Pravo!');
    dashboard = new DashboardVC({
      template: 'dashboard',
      position: 'append'
    });
    window.Pravo = {};
    return Pravo.cleanLocalArtworks = function() {
      return dashboard.gallery.artworks.save({
        only: 'nil'
      });
    };
  });
});
