// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['found/error'], function(Errors) {
  var ApiFactory;
  ApiFactory = (function() {
    function ApiFactory(option) {
      this.create = bind(this.create, this);
      if (option == null) {
        option = {};
      }
      this.root = option.root || '';
      this.timeout = option.timeout || 1000 * 60;
    }

    ApiFactory.prototype.request = function(option) {
      return $.ajax(option);
    };

    ApiFactory.prototype.create = function(option) {
      if (option == null) {
        option = {};
      }
      return (function(_this) {
        return function(data, callback) {
          var contentType, method, timeout, url;
          console.log(data);
          if (!data) {
            data = {};
          }
          method = option.method || 'GET';
          url = '';
          if (option.url) {
            url = option.url;
          } else {
            url = (_this.root || '') + option.path;
          }
          timeout = _this.timeout;
          if (method.toUpperCase() === 'GET') {
            contentType = 'application/x-www-form-urlencoded';
            data = data;
          } else {
            contentType = 'application/json';
            data = JSON.stringify(data);
          }
          return _this.request({
            type: method,
            data: data,
            url: url,
            success: function(data) {
              if (data && data.error) {
                return callback(data, null);
              } else {
                return callback(null, data);
              }
            },
            error: function(xhr, state) {
              return callback(state);
            }
          });
        };
      })(this);
    };

    return ApiFactory;

  })();
  return ApiFactory;
});
