// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['found/error'], function(Errors) {
  var ApiFactory;
  ApiFactory = (function() {
    function ApiFactory(option) {
      this.create = __bind(this.create, this);
      if (option == null) {
        option = {};
      }
      this.root = option.root || '';
      this.timeout = option.timeout || 1000 * 60;
    }

    ApiFactory.prototype.request = function(option) {
      return $.ajax(option);
    };

    ApiFactory.prototype.create = function(option) {
      if (option == null) {
        option = {};
      }
      return (function(_this) {
        return function(data, callback) {
          var contentType, method, timeout, url;
          console.log(data);
          if (!data) {
            data = {};
          }
          method = option.method || 'GET';
          url = '';
          if (option.url) {
            url = option.url;
          } else {
            url = (_this.root || '') + option.path;
          }
          timeout = _this.timeout;
          if (method.toUpperCase() === 'GET') {
            contentType = 'application/x-www-form-urlencoded';
            data = data;
          } else {
            contentType = 'application/json';
            data = JSON.stringify(data);
          }
          return _this.request({
            type: method,
            data: data,
            url: url,
            timeout: timeout,
            dataType: 'json',
            contentType: contentType,
            success: function(data) {
              if (data && data.error) {
                return callback(data, null);
              } else {
                return callback(null, data);
              }
            },
            error: function(xhr, state) {
              var e;
              console.debug('fail');
              if (state === 'timeout') {
                return callback(new Errors.Timeout);
              } else if (state === 'abort') {
                return callback(new Errors.Abort);
              } else {
                try {
                  data = JSON.parse(xhr.responseText);
                } catch (_error) {
                  e = _error;
                  callback(new Errors.UnkownError, xhr.responseText);
                }
                return;
                return callback({
                  code: data.code,
                  message: data.error
                });
              }
            }
          });
        };
      })(this);
    };

    return ApiFactory;

  })();
  return ApiFactory;
});
