// Generated by CoffeeScript 1.9.3
define(['found/api-factory'], function(ApiFactory) {
  var API, GET, POST, create;
  API = new ApiFactory({
    root: 'https://konachan.com/'
  });
  create = API.create.bind(API);
  GET = "GET";
  POST = "POST";
  API.signUp = create({
    method: POST,
    path: 'me/register'
  });
  API.signIn = create({
    method: POST,
    path: 'me/session'
  });
  API.getArtworks = create({
    method: GET,
    path: 'post.json?limit=5&tags=hatsune_miku'
  });
  return API;
});
