// Generated by CoffeeScript 1.7.1
define(['found/api-factory'], function(ApiFactory) {
  var API, GET, POST, create;
  API = new ApiFactory({
    root: 'http://211.155.86.150:9999/'
  });
  create = API.create.bind(API);
  GET = "GET";
  POST = "POST";
  API.signUp = create({
    method: POST,
    path: 'me/register'
  });
  API.signIn = create({
    method: POST,
    path: 'me/session'
  });
  API.getArtworks = create({
    method: GET,
    path: 'artworks'
  });
  return API;
});
