// Generated by CoffeeScript 1.7.1
define(['jquery', 'lib/underscore'], function() {
  var TPL;
  TPL = {};
  TPL.getTpl = function(tpl) {
    return $("[data-tpl='" + tpl + "']").html();
  };
  return TPL;
});
