// Generated by CoffeeScript 1.7.1
define([], function() {
  var Util;
  Util = {};
  Util.resolveUrl = function() {
    var a, arg, base, head, numUrls, resolved, _i, _len;
    console.log(arguments);
    numUrls = arguments.length;
    if (numUrls === 0) {
      return false;
    }
    base = document.createElement('base');
    base.href = arguments[0];
    if (numUrls === 1) {
      return base.href;
    }
    head = (document.getElementsByTagName('head'))[0];
    head.insertBefore(base, head.firstChild);
    a = document.createElement('a');
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      arg = arguments[_i];
      a.href = arg;
      resolved = a.href;
      base.href = resolved;
    }
    head.removeChild(base);
    return resolved;
  };
  return Util;
});
