// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(['found/vc', 'vc/gallery'], function(VC, GalleryVC) {
  var DashboardVC;
  DashboardVC = (function(superClass) {
    extend(DashboardVC, superClass);

    function DashboardVC() {
      return DashboardVC.__super__.constructor.apply(this, arguments);
    }

    DashboardVC.prototype.initialize = function(opt) {
      DashboardVC.__super__.initialize.call(this, opt);
      return this.render();
    };

    DashboardVC.prototype.update = function() {
      console.log('Dashboard Rendered');
      return this.galleryVC = new GalleryVC({
        $root: this.ui.$gallery,
        template: 'gallery'
      });
    };

    return DashboardVC;

  })(VC);
  return DashboardVC;
});
