// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(['lib/underscore', 'found/c', 'mcs/Artwork', 'found/api'], function(_, C, Artwork, API) {
  var Artworks;
  Artworks = (function(superClass) {
    extend(Artworks, superClass);

    function Artworks() {
      this.onChangeIsCurrent = bind(this.onChangeIsCurrent, this);
      return Artworks.__super__.constructor.apply(this, arguments);
    }

    Artworks.prototype.model = Artwork;

    Artworks.prototype.initialize = function() {
      this.currentIndex = 0;
      this.isSettingLocal = false;
      return this.on({
        "change:isCurrent": this.onChangeIsCurrent
      });
    };

    Artworks.prototype.onChangeIsCurrent = function() {
      return this.updateCurrentIndex();
    };

    Artworks.prototype.update = function() {
      console.log("Updated to " + this.length + " Artworks");
      return console.log(this.models);
    };

    Artworks.prototype.getAlter = function() {
      if (this.length === 0) {
        return this.add([
          {
            path: '1.png',
            isCurrent: true
          }, {
            path: '2.png'
          }, {
            path: '3.png'
          }, {
            path: '0.png'
          }
        ]);
      }
    };

    Artworks.prototype.getLocal = function() {
      console.debug("Getting Local Artworks");
      return chrome.storage.local.get('artworks', (function(_this) {
        return function(data) {
          var j, len, rawArtwork, rawArtworks;
          if (!data.artworks) {
            console.log('No Local Artworks');
          } else {
            _this.reset();
            rawArtworks = JSON.parse(data.artworks || {});
            for (j = 0, len = rawArtworks.length; j < len; j++) {
              rawArtwork = rawArtworks[j];
              console.log("New Artwork from Local");
              _this.add(rawArtwork);
            }
          }
          _this.trigger("gotLocal");
          console.debug("Local Artworks Got:");
          return console.log(_this.models);
        };
      })(this));
    };

    Artworks.prototype.setLocal = function() {
      var artworksJSON;
      this.isSettingLocal = true;
      console.debug('Setting LocalArtworks');
      artworksJSON = JSON.stringify(this.models);
      console.log(artworksJSON);
      chrome.storage.local.set({
        'artworks': artworksJSON
      }, (function(_this) {
        return function() {
          _this.trigger("setLocal");
          console.debug("Local Artworks Set:");
          return console.log(_this.models);
        };
      })(this));
      return this.isSettingLocal = false;
    };

    Artworks.prototype.getServer = function() {
      console.debug("Getting Server Artworks");
      return API.getArtworks({}, (function(_this) {
        return function(err, data) {
          var j, len, rawArtwork, refArtwork, refArtworks;
          refArtworks = [];
          console.debug("Server Data:");
          console.log(data);
          if ((data != null ? data.length : void 0) > 0) {
            _this.reset();
            refArtworks = data;
            for (j = 0, len = refArtworks.length; j < len; j++) {
              refArtwork = refArtworks[j];
              rawArtwork = {
                id: refArtwork.id,
                url: refArtwork.file_url
              };
              _this.add(rawArtwork);
              _this.at(0).set('isCurrent', true);
            }
            _this.trigger("gotServer");
            console.debug("Server Artworks Get:");
            return console.log(_this.models);
          }
        };
      })(this));
    };

    Artworks.prototype.loop = function() {
      this.toggleCurrent();
      if (this.currentIndex < this.length - 1) {
        this.currentIndex++;
      } else {
        this.currentIndex = 0;
      }
      return this.toggleCurrent();
    };

    Artworks.prototype.toggleCurrent = function() {
      console.debug('Is Artworks C:');
      console.log(this);
      if ((this.at(this.currentIndex)).get('isCurrent')) {
        return (this.at(this.currentIndex)).set('isCurrent', false);
      } else {
        return (this.at(this.currentIndex)).set('isCurrent', true);
      }
    };

    Artworks.prototype.updateCurrentIndex = function() {
      var artwork, i, j, len, ref, results;
      ref = this.models;
      results = [];
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        artwork = ref[i];
        if (artwork.get('isCurrent')) {
          this.currentIndex = i;
          results.push(console.error(i));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    return Artworks;

  })(C);
  return Artworks;
});
