// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(['lib/underscore', 'found/m'], function(_, M) {
  var Artwork;
  Artwork = (function(superClass) {
    extend(Artwork, superClass);

    function Artwork() {
      return Artwork.__super__.constructor.apply(this, arguments);
    }

    Artwork.prototype.defaults = {
      "root": "../../img/artwork",
      "path": "0.png",
      "isCurrent": false
    };

    Artwork.prototype.initialize = function() {
      console.log("New Artwork");
      this.set("src", (this.get('root')) + "/" + (this.get('path')));
      return console.log(this);
    };

    return Artwork;

  })(M);
  return Artwork;
});
