// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(['lib/underscore', 'found/vc', 'vcs/gallery'], function(_, VC, GalleryVC) {
  var Dashboard;
  Dashboard = (function(superClass) {
    extend(Dashboard, superClass);

    function Dashboard() {
      this.onClickPravo = bind(this.onClickPravo, this);
      return Dashboard.__super__.constructor.apply(this, arguments);
    }

    Dashboard.prototype.events = {
      "click [data-ui='pravo']": 'onClickPravo'
    };

    Dashboard.prototype.onClickPravo = function() {
      return console.error('Pravo!');
    };

    Dashboard.prototype.initialize = function(option) {
      Dashboard.__super__.initialize.call(this, option);
      this.render();
      return console.log(this.ui.$gallery);
    };

    Dashboard.prototype.update = function() {
      console.log('Pravo!');
      console.log('Dashboard');
      return this.gallery = new GalleryVC({
        root: 'gallery',
        template: 'gallery'
      });
    };

    return Dashboard;

  })(VC);
  return Dashboard;
});
