// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['lib/underscore', 'found/vc', 'vcs/artwork'], function(_, VC, Artwork) {
  var Gallery;
  Gallery = (function(_super) {
    __extends(Gallery, _super);

    function Gallery(option) {
      Gallery.__super__.constructor.call(this, option);
      this.render();
    }

    Gallery.prototype.update = function() {
      console.log("Gallery updated");
      return this.renderArtwork();
    };

    Gallery.prototype.renderArtwork = function() {
      var artwork;
      return artwork = new Artwork({
        root: 'artworkCollection',
        block: 'ap',
        template: 'artwork'
      });
    };

    return Gallery;

  })(VC);
  return Gallery;
});
