// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(['lib/underscore', 'found/vc', 'vcs/gallery'], function(_, VC, GalleryVC) {
  var Pravo;
  Pravo = (function(superClass) {
    extend(Pravo, superClass);

    function Pravo() {
      return Pravo.__super__.constructor.apply(this, arguments);
    }

    Pravo.prototype.initialize = function(option) {
      Pravo.__super__.initialize.call(this, option);
      return this.render();
    };

    Pravo.prototype.update = function() {
      console.log('Pravo!');
      return new GalleryVC({
        root: 'gallery',
        template: 'gallery'
      });
    };

    return Pravo;

  })(VC);
  return Pravo;
});
